[package]
name = "bthint"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
description = "Discord bot to remind users to use backticks"

[dependencies]
anyhow = "1.0.36"
async-trait = "0.1.42"
config = "0.10.1"
futures = "0.3.8"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
serenity = "0.9.2"
tokio = {version = "1.0.1", features = ["full"]}
